In [36]:
import pandas as pd
import numpy as np

In [37]:
n = pd.read_csv('/content/Weather Data.csv')

In [38]:
n.head()

Date/Time  Temp_C  Dew  Rel  Wind  Visibility_km  Press_kPa  \
0  1/1/2012 0:00    -1.8 -3.9   86     4            8.0     101.24   
1  1/1/2012 1:00    -1.8 -3.7   87     4            8.0     101.24   
2  1/1/2012 2:00    -1.8 -3.4   89     7            4.0     101.26   
3  1/1/2012 3:00    -1.5 -3.2   88     6            4.0     101.27   
4  1/1/2012 4:00    -1.5 -3.3   88     7            4.8     101.23   

                Weather  
0                   Fog  
1                   Fog  
2  Freezing Drizzle,Fog  
3  Freezing Drizzle,Fog  
4                   Fog

In [69]:
n

Date/Time  Temp_C  Dew  Rel  Wind  Visibility_km  Press_kPa  \
0        1/1/2012 0:00    -1.8 -3.9   86     4            8.0     101.24   
1        1/1/2012 1:00    -1.8 -3.7   87     4            8.0     101.24   
2        1/1/2012 2:00    -1.8 -3.4   89     7            4.0     101.26   
3        1/1/2012 3:00    -1.5 -3.2   88     6            4.0     101.27   
4        1/1/2012 4:00    -1.5 -3.3   88     7            4.8     101.23   
...                ...     ...  ...  ...   ...            ...        ...   
8779  12/31/2012 19:00     0.1 -2.7   81    30            9.7     100.13   
8780  12/31/2012 20:00     0.2 -2.4   83    24            9.7     100.03   
8781  12/31/2012 21:00    -0.5 -1.5   93    28            4.8      99.95   
8782  12/31/2012 22:00    -0.2 -1.8   89    28            9.7      99.91   
8783  12/31/2012 23:00     0.0 -2.1   86    30           11.3      99.89   

                   Weather  
0                      Fog  
1                      Fog  
2     Freezing Drizzle,Fog  
3     Freezing Drizzle,Fog  
4                      Fog  
...                    ...  
8779                  Snow  
8780                  Snow  
8781                  Snow  
8782                  Snow  
8783                  Snow  

[8784 rows x 8 columns]

In [ ]:
if n[Date/Time]

In [59]:
n.isna().sum()

Date/Time        0
Temp_C           0
Dew              0
Rel              0
Wind             0
Visibility_km    0
Press_kPa        0
Weather          0
dtype: int64

In [40]:
X = n[['Temp_C',	'Dew','Rel',	'Wind',	'Visibility_km',	'Press_kPa'	]]
y = n['Weather']

AttributeError: ignored

In [41]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score,r2_score

In [53]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
y=le.fit_transform(y)


In [54]:
x_t , x_te , y_t , y_te  = train_test_split(X,y,test_size=0.2,random_state=0)

In [55]:
x_t

Temp_C   Dew  Rel  Wind  Visibility_km  Press_kPa
4543    18.8  12.2   65    20           48.3     100.83
3318    10.1   3.3   63    11           48.3     101.84
3656    15.2   3.5   45    11           48.3     101.48
6945     6.0   1.3   72    19           24.1     100.27
7427     1.7  -7.4   51    17           48.3     101.47
...      ...   ...  ...   ...            ...        ...
4373    20.2  12.3   60     0           24.1     100.32
7891    -0.9  -5.0   74    22           19.3      99.90
4859    24.7  13.7   50     9           48.3     101.39
3264    14.6  12.6   88     4           25.0     100.71
2732     5.7   3.6   86    41           25.0      98.54

[7027 rows x 6 columns]

In [56]:
x_te

Temp_C   Dew  Rel  Wind  Visibility_km  Press_kPa
541      2.5  -1.5   75    22           48.3     101.14
6353    17.3  15.5   89     4           24.1     100.88
2578    10.9  -1.3   43    41           48.3     101.51
1733     5.8   1.1   72     6           25.0     100.71
8364     2.8  -1.5   73    17           24.1     101.33
...      ...   ...  ...   ...            ...        ...
1978    14.5   0.1   37    17           48.3     101.93
3618    22.4   8.4   41    20           48.3     100.06
7207    12.3  10.8   91     6            4.0     101.42
8030    -9.0 -15.6   59     6           48.3     103.15
3756    20.3   4.9   36    20           48.3     100.97

[1757 rows x 6 columns]

In [57]:
y_t

array([19, 19,  1, ..., 19,  0,  1])

In [58]:
y_te

array([ 1,  1, 19, ...,  7, 23, 19])

In [62]:
model = RandomForestClassifier()

In [64]:
model.fit(x_t,y_t)

RandomForestClassifier()

In [65]:
p = model.predict(x_te)

In [66]:
p

array([ 1, 19, 19, ...,  3, 23,  1])

In [67]:
r2_score(p,y_te)

-0.12515881082751434

In [68]:
accuracy_score(p,y_te)

0.5406943653955606

In [74]:
import pickle
pickle.dump(model, open('p.pkl', 'wb'))